"""Generate coast table and update `config.h` mass/air-density constants."""

from __future__ import annotations

import re
from pathlib import Path

import numpy as np

# -----------------------------------------------------------------------------
# User-editable configuration
# -----------------------------------------------------------------------------
MASS_KG = 0.608
TEMP_F = 68.0
HUMIDITY_PCT = 55.0
PRESSURE_HPA = 1015.0

N_VEL = 20
N_CD = 20
VEL_MIN = 0.0
VEL_MAX = 80.0
CD_MIN = 0.0
CD_MAX = 6.0

OUTPUT_PY = "coast_table.py"
OUTPUT_CPP = "../include/coast_table.h"
CONFIG_H = "../include/config.h"

# Constants
G = 9.80665  # m/s^2
AREA = (np.pi * (6.6 / 100.0) ** 2) / 4.0  # m^2
DT = 0.001  # 1 kHz for lookup generation accuracy


def compute_air_density(temp_f: float, humidity_pct: float,
                        pressure_hpa: float = 1013.25) -> float:
    """Compute moist-air density from Fahrenheit temperature and RH%."""
    temp_c = (temp_f - 32.0) * (5.0 / 9.0)
    temp_k = temp_c + 273.15
    rh = max(0.0, min(100.0, humidity_pct)) / 100.0
    pressure_pa = pressure_hpa * 100.0

    # Magnus formula for saturation vapor pressure over water (Pa)
    sat_vapor_pa = 610.94 * np.exp((17.625 * temp_c) / (temp_c + 243.04))
    vapor_pa = rh * sat_vapor_pa
    dry_air_pa = pressure_pa - vapor_pa

    # Gas constants for dry air and water vapor.
    r_dry = 287.05
    r_vapor = 461.495
    rho = (dry_air_pa / (r_dry * temp_k)) + (vapor_pa / (r_vapor * temp_k))
    return float(rho)


def simulate_coast(initial_velocity: float, cd: float, mass_kg: float,
                   rho_air: float) -> float:
    """Simulate coast and return altitude gained until apogee."""
    vel = initial_velocity
    alt_gained = 0.0
    t = 0.0

    while vel > 0.0 and t < 20.0:
        drag = -0.5 * rho_air * AREA * cd * vel * abs(vel)
        weight = -mass_kg * G
        accel = (drag + weight) / mass_kg

        vel += accel * DT
        alt_gained += vel * DT
        t += DT

    return max(0.0, alt_gained)


def generate_coast_table(mass_kg: float,
                         rho_air: float,
                         n_vel: int = 20,
                         n_cd: int = 20,
                         vel_min: float = 0.0,
                         vel_max: float = 80.0,
                         cd_min: float = 0.0,
                         cd_max: float = 5.5):
    """Generate the [velocity, Cd] -> coast altitude gain lookup table."""
    vel_range = np.linspace(vel_min, vel_max, n_vel)
    cd_range = np.linspace(cd_min, cd_max, n_cd)
    altitude_table = np.zeros((n_vel, n_cd), dtype=float)

    print(f"Generating {n_vel}x{n_cd} coast table")
    print(f"Mass: {mass_kg:.4f} kg, Air density: {rho_air:.6f} kg/m^3")
    print(
        f"Velocity range: {vel_min:.1f}-{vel_max:.1f} m/s, "
        f"Cd range: {cd_min:.2f}-{cd_max:.2f}"
    )

    for i, vel in enumerate(vel_range):
        for j, cd in enumerate(cd_range):
            altitude_table[i, j] = simulate_coast(vel, cd, mass_kg, rho_air)
        if (i + 1) % 4 == 0:
            print(f"Progress: {i + 1}/{n_vel}")

    print(
        f"Table generation complete. Altitude span: "
        f"{np.min(altitude_table):.2f}-{np.max(altitude_table):.2f} m"
    )
    return vel_range, cd_range, altitude_table


def save_coast_table_to_file(vel_range: np.ndarray, cd_range: np.ndarray,
                             altitude_table: np.ndarray,
                             filename: Path) -> None:
    """Save coast lookup table as a Python module."""
    with filename.open("w") as f:
        f.write('"""\n')
        f.write('Coast phase lookup table for apogee prediction.\n')
        f.write('Auto-generated by generate_coast_table.py\n')
        f.write('"""\n')
        f.write('import numpy as np\n\n')
        f.write(f'VEL_RANGE = np.array({vel_range.tolist()})\n\n')
        f.write(f'CD_RANGE = np.array({cd_range.tolist()})\n\n')
        f.write('ALTITUDE_TABLE = np.array([\n')
        for row in altitude_table:
            f.write('    ' + str(row.tolist()) + ',\n')
        f.write('])\n')
    print(f"Saved Python coast table: {filename}")


def save_coast_table_to_cpp(vel_range: np.ndarray,
                            cd_range: np.ndarray,
                            altitude_table: np.ndarray,
                            filename: Path) -> None:
    """Save coast lookup table as a C++ header."""
    n_vel = len(vel_range)
    n_cd = len(cd_range)

    with filename.open("w") as f:
        f.write("#ifndef COAST_TABLE_H\n")
        f.write("#define COAST_TABLE_H\n\n")
        f.write("// Auto-generated by generate_coast_table.py\n")
        f.write(
            f"// {n_vel}x{n_cd} table, vel {vel_range[0]:.1f}-"
            f"{vel_range[-1]:.1f} m/s, Cd {cd_range[0]:.2f}-"
            f"{cd_range[-1]:.2f}\n\n"
        )
        f.write(f"constexpr int COAST_N_VEL = {n_vel};\n")
        f.write(f"constexpr int COAST_N_CD = {n_cd};\n\n")
        f.write(f"constexpr float COAST_VEL_MIN = {vel_range[0]:.1f}f;\n")
        f.write(f"constexpr float COAST_VEL_MAX = {vel_range[-1]:.1f}f;\n")
        f.write(
            "constexpr float COAST_VEL_STEP = "
            f"{(vel_range[-1] - vel_range[0]) / (n_vel - 1):.10f}f;\n"
        )
        f.write(f"constexpr float COAST_CD_MIN = {cd_range[0]:.2f}f;\n")
        f.write(f"constexpr float COAST_CD_MAX = {cd_range[-1]:.2f}f;\n")
        f.write(
            "constexpr float COAST_CD_STEP = "
            f"{(cd_range[-1] - cd_range[0]) / (n_cd - 1):.10f}f;\n\n"
        )
        f.write("// Altitude gain table [n_vel][n_cd] (meters)\n")
        f.write(f"constexpr float COAST_ALTITUDE_TABLE[{n_vel}][{n_cd}] = {{\n")
        for row in altitude_table:
            vals = ", ".join(f"{v:.6f}f" for v in row)
            f.write(f"    {{{vals}}},\n")
        f.write("};\n\n")
        f.write("#endif  // COAST_TABLE_H\n")

    print(f"Saved C++ coast table header: {filename}")


def update_config_header(config_path: Path, mass_kg: float, rho_air: float,
                         temp_f: float, humidity_pct: float) -> None:
    """Update `MASS` and `RHO` macros in `config.h`."""
    content = config_path.read_text()

    mass_line = (
        f"#define MASS {mass_kg:.6f}f         "
        "// kg (auto-generated by generate_coast_table.py)"
    )
    rho_line = (
        f"#define RHO {rho_air:.6f}f                                              "
        f"// kg/m^3 (from {temp_f:.1f}F, {humidity_pct:.1f}% RH)"
    )

    content_new, mass_count = re.subn(
        r"^#define\s+MASS\s+.*$", mass_line, content, flags=re.MULTILINE
    )
    content_new, rho_count = re.subn(
        r"^#define\s+RHO\s+.*$", rho_line, content_new, flags=re.MULTILINE
    )

    if mass_count == 0 or rho_count == 0:
        raise RuntimeError(
            "Failed to update MASS/RHO in config.h. "
            "Expected '#define MASS' and '#define RHO' lines."
        )

    config_path.write_text(content_new)
    print(f"Updated config constants in {config_path}")


def main() -> None:
    here = Path(__file__).resolve().parent
    out_py = (here / OUTPUT_PY).resolve()
    out_cpp = (here / OUTPUT_CPP).resolve()
    config_h = (here / CONFIG_H).resolve()

    rho_air = compute_air_density(TEMP_F, HUMIDITY_PCT, PRESSURE_HPA)
    print(
        f"Computed rho = {rho_air:.6f} kg/m^3 "
        f"at {TEMP_F:.1f}F, {HUMIDITY_PCT:.1f}% RH, "
        f"{PRESSURE_HPA:.2f} hPa"
    )

    vel_range, cd_range, altitude_table = generate_coast_table(
        mass_kg=MASS_KG,
        rho_air=rho_air,
        n_vel=N_VEL,
        n_cd=N_CD,
        vel_min=VEL_MIN,
        vel_max=VEL_MAX,
        cd_min=CD_MIN,
        cd_max=CD_MAX,
    )

    save_coast_table_to_file(vel_range, cd_range, altitude_table, out_py)
    save_coast_table_to_cpp(vel_range, cd_range, altitude_table, out_cpp)
    update_config_header(config_h, MASS_KG, rho_air, TEMP_F,
                         HUMIDITY_PCT)

    print("Done")


if __name__ == "__main__":
    main()