"""Airbrakes V3 desktop ground station.

This is intentionally a single-file desktop app so it can be packaged as a
Windows executable later without changing the workflow. It uses the firmware's
existing serial protocol and the existing PlatformIO project in this folder.
"""

from __future__ import annotations

import csv
import math
import os
import re
import shutil
import struct
import subprocess
import sys
import threading
import time
import tkinter as tk
from datetime import datetime
from pathlib import Path
from tkinter import filedialog, messagebox, ttk

try:
    import serial
    from serial.tools import list_ports
except ImportError:
    serial = None
    list_ports = None

try:
    from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
    from matplotlib.figure import Figure
except ImportError:
    FigureCanvasTkAgg = None
    Figure = None


ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "include" / "config.h"
COAST_HEADER = ROOT / "include" / "coast_table.h"
FLIGHT_DIR = ROOT / "flight_data"
RECORD_FORMAT = "<I14fII"
RECORD_SIZE = struct.calcsize(RECORD_FORMAT)
STATE_NAMES = ["IDLE", "PAD", "BOOST", "CONTROL", "DESCENT", "LANDED"]


def density(temp_f, humidity, pressure_hpa):
    temp_c = (temp_f - 32.0) * 5.0 / 9.0
    temp_k = temp_c + 273.15
    rh = max(0.0, min(100.0, humidity)) / 100.0
    pressure_pa = pressure_hpa * 100.0
    sat = 610.94 * math.exp((17.625 * temp_c) / (temp_c + 243.04))
    vapor = rh * sat
    return (pressure_pa - vapor) / (287.05 * temp_k) + vapor / (461.495 * temp_k)


def coast_height(velocity, cd, mass, rho):
    vel = velocity
    height = 0.0
    dt = 0.001
    for _ in range(20000):
        if vel <= 0:
            break
        accel = (-0.5 * rho * ((math.pi * (0.066 ** 2)) / 4.0) * cd * vel * abs(vel) - mass * 9.80665) / mass
        vel += accel * dt
        height += vel * dt
    return max(0.0, height)


def write_coast_table(mass, rho):
    n_vel, n_cd = 20, 20
    vel_min, vel_max, cd_min, cd_max = 0.0, 80.0, 0.0, 6.0
    velocities = [vel_min + (vel_max - vel_min) * i / (n_vel - 1) for i in range(n_vel)]
    cds = [cd_min + (cd_max - cd_min) * i / (n_cd - 1) for i in range(n_cd)]
    table = [[coast_height(v, cd, mass, rho) for cd in cds] for v in velocities]
    lines = [
        "#ifndef COAST_TABLE_H", "#define COAST_TABLE_H", "",
        "// Auto-generated by Airbrakes V3 Ground Station.",
        f"// {n_vel}x{n_cd} table, vel {vel_min:.1f}-{vel_max:.1f} m/s, Cd {cd_min:.2f}-{cd_max:.2f}",
        "", f"constexpr int COAST_N_VEL = {n_vel};", f"constexpr int COAST_N_CD = {n_cd};", "",
        f"constexpr float COAST_VEL_MIN = {vel_min:.1f}f;",
        f"constexpr float COAST_VEL_MAX = {vel_max:.1f}f;",
        f"constexpr float COAST_VEL_STEP = {(vel_max - vel_min) / (n_vel - 1):.10f}f;",
        f"constexpr float COAST_CD_MIN = {cd_min:.2f}f;", f"constexpr float COAST_CD_MAX = {cd_max:.2f}f;",
        f"constexpr float COAST_CD_STEP = {(cd_max - cd_min) / (n_cd - 1):.10f}f;", "",
        f"constexpr float COAST_ALTITUDE_TABLE[{n_vel}][{n_cd}] = {{",
    ]
    lines += ["    {" + ", ".join(f"{value:.6f}f" for value in row) + "}," for row in table]
    lines += ["};", "", "#endif  // COAST_TABLE_H", ""]
    COAST_HEADER.write_text("\n".join(lines), encoding="ascii")
    return velocities, cds, table


def update_macro(name, value, suffix="f"):
    text = CONFIG.read_text(encoding="utf-8")
    pattern = rf"^#define\s+{name}\s+.*$"
    updated, count = re.subn(pattern, f"#define {name} {value}{suffix}", text, flags=re.MULTILINE)
    if not count:
        raise ValueError(f"Could not find {name} in include/config.h")
    CONFIG.write_text(updated, encoding="ascii")


def macro(name, default=""):
    match = re.search(rf"^#define\s+{name}\s+([^\s/]+)", CONFIG.read_text(encoding="utf-8"), re.MULTILINE)
    return match.group(1).rstrip("f") if match else default


def board_ports():
    if list_ports is None:
        return []
    ports = []
    for port in list_ports.comports():
        text = " ".join(str(x or "") for x in (port.device, port.description, port.manufacturer, port.product))
        score = 0 if any(x.lower() in text.lower() for x in ("srijan", "airbrakes v3")) else 1
        if any(x.lower() in text.lower() for x in ("pico", "rp2040", "rp2350", "airbrakes", "srijan")):
            ports.insert(0 if score == 0 else len(ports), (port.device, text))
    return ports


class GroundStation(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("Airbrakes V3 Ground Station")
        self.geometry("1180x780")
        self.minsize(980, 650)
        self.port = None
        self.flight_rows = []
        self.records = []
        self.status = tk.StringVar(value="Ready. Connect the flight computer over USB.")
        self.port_var = tk.StringVar()
        self._build()
        self.refresh_ports()
        self.load_settings()

    def _build(self):
        header = ttk.Frame(self, padding=(18, 14))
        header.pack(fill="x")
        ttk.Label(header, text="AIRBRAKES V3", font=("Segoe UI", 18, "bold")).pack(side="left")
        ttk.Label(header, text="  Ground Station", font=("Segoe UI", 12)).pack(side="left", pady=(5, 0))
        self.connection_label = ttk.Label(header, text="Not connected", foreground="#a33")
        self.connection_label.pack(side="right", pady=(5, 0))

        bar = ttk.Frame(self, padding=(18, 0, 18, 10))
        bar.pack(fill="x")
        ttk.Label(bar, text="Flight computer:").pack(side="left")
        self.port_box = ttk.Combobox(bar, textvariable=self.port_var, width=32, state="readonly")
        self.port_box.pack(side="left", padx=8)
        ttk.Button(bar, text="Refresh", command=self.refresh_ports).pack(side="left")
        ttk.Button(bar, text="Connect", command=self.connect).pack(side="left", padx=(8, 0))

        self.tabs = ttk.Notebook(self)
        self.tabs.pack(fill="both", expand=True, padx=18, pady=(0, 10))
        self.ready_tab = ttk.Frame(self.tabs, padding=18)
        self.flights_tab = ttk.Frame(self.tabs, padding=18)
        self.analysis_tab = ttk.Frame(self.tabs, padding=18)
        self.settings_tab = ttk.Frame(self.tabs, padding=18)
        for tab, label in ((self.ready_tab, "Flight Ready"), (self.flights_tab, "Flights"), (self.analysis_tab, "Analysis"), (self.settings_tab, "Launch Setup")):
            self.tabs.add(tab, text=label)
        self.build_ready_tab(); self.build_flights_tab(); self.build_analysis_tab(); self.build_settings_tab()
        ttk.Label(self, textvariable=self.status, relief="sunken", anchor="w", padding=6).pack(fill="x", side="bottom")

    def build_ready_tab(self):
        ttk.Label(self.ready_tab, text="Prepare the flight computer", font=("Segoe UI", 16, "bold")).pack(anchor="w")
        ttk.Label(self.ready_tab, text="Generate the coast model, verify the board, build the firmware, and upload it in one step.").pack(anchor="w", pady=(4, 18))
        actions = ttk.Frame(self.ready_tab); actions.pack(fill="x")
        ttk.Button(actions, text="Generate Coast Table", command=self.generate).pack(side="left")
        ttk.Button(actions, text="Build Firmware", command=lambda: self.run_pio("run")).pack(side="left", padx=8)
        ttk.Button(actions, text="Flash Flight Computer", command=self.flash).pack(side="left")
        ttk.Button(actions, text="Download All Flights", command=self.download_all).pack(side="left", padx=8)
        self.ready_text = tk.Text(self.ready_tab, height=20, state="disabled", background="#f7f7f7")
        self.ready_text.pack(fill="both", expand=True, pady=(20, 0))
        self.log("The app will show build and connection results here.")

    def build_flights_tab(self):
        top = ttk.Frame(self.flights_tab); top.pack(fill="x")
        ttk.Button(top, text="Refresh Flights", command=self.list_flights).pack(side="left")
        ttk.Button(top, text="Download Selected", command=self.download_selected).pack(side="left", padx=8)
        ttk.Button(top, text="Delete Selected", command=self.delete_selected).pack(side="left")
        self.flight_list = tk.Listbox(self.flights_tab, height=10, selectmode="browse")
        self.flight_list.pack(fill="both", expand=True, pady=12)
        ttk.Label(self.flights_tab, text="Downloaded files are saved in the project's flight_data folder.").pack(anchor="w")

    def build_analysis_tab(self):
        top = ttk.Frame(self.analysis_tab); top.pack(fill="x")
        self.file_var = tk.StringVar()
        self.file_box = ttk.Combobox(top, textvariable=self.file_var, state="readonly", width=65)
        self.file_box.pack(side="left")
        ttk.Button(top, text="Refresh", command=self.refresh_files).pack(side="left", padx=8)
        ttk.Button(top, text="Plot Flight", command=self.plot_selected).pack(side="left")
        self.plot_frame = ttk.Frame(self.analysis_tab); self.plot_frame.pack(fill="both", expand=True, pady=(12, 0))
        self.refresh_files()

    def build_settings_tab(self):
        ttk.Label(self.settings_tab, text="Launch conditions and controller configuration", font=("Segoe UI", 16, "bold")).grid(row=0, column=0, columnspan=4, sticky="w", pady=(0, 14))
        self.fields = {}
        specs = [("MASS", "Rocket mass", "kg"), ("TEMP_F", "Temperature", "F"), ("HUMIDITY", "Relative humidity", "%"), ("PRESSURE", "Pressure", "hPa"), ("TARGET_ALTITUDE", "Target apogee", "m"), ("BASE_CD", "Base Cd", ""), ("MOTOR_MIN", "Brake closed", "position"), ("MOTOR_MAX", "Brake open", "position")]
        for index, (name, label, unit) in enumerate(specs, start=1):
            row, col = divmod(index - 1, 2)
            ttk.Label(self.settings_tab, text=f"{label} ({unit})" if unit else label).grid(row=row, column=col * 2, sticky="w", padx=(0, 8), pady=7)
            var = tk.StringVar(); self.fields[name] = var
            ttk.Entry(self.settings_tab, textvariable=var, width=18).grid(row=row, column=col * 2 + 1, sticky="w", padx=(0, 35), pady=7)
        ttk.Button(self.settings_tab, text="Save Settings and Generate Coast Table", command=self.save_settings).grid(row=5, column=0, columnspan=2, sticky="w", pady=(18, 0))
        ttk.Label(self.settings_tab, text="Settings are written to include/config.h and become active after flashing.", foreground="#555").grid(row=6, column=0, columnspan=4, sticky="w", pady=14)

    def log(self, text):
        self.ready_text.configure(state="normal"); self.ready_text.insert("end", f"{text}\n"); self.ready_text.see("end"); self.ready_text.configure(state="disabled")
        self.status.set(text)

    def load_settings(self):
        for name in ("MASS", "TARGET_ALTITUDE", "BASE_CD", "MOTOR_MIN", "MOTOR_MAX"):
            self.fields[name].set(macro(name))
        self.fields["TEMP_F"].set("68.0"); self.fields["HUMIDITY"].set("55.0"); self.fields["PRESSURE"].set("1015.0")

    def refresh_ports(self):
        ports = board_ports(); self.port_box["values"] = [f"{d} | {t[:70]}" for d, t in ports]
        if ports: self.port_box.current(0); self.log(f"Detected Airbrakes-compatible board on {ports[0][0]}.")
        else: self.log("No Airbrakes board detected. Connect it over USB and press Refresh.")

    def selected_port(self):
        value = self.port_var.get()
        return value.split(" | ", 1)[0] if value else None

    def connect(self):
        if serial is None: return messagebox.showerror("Missing dependency", "Install the app dependencies first: pyserial and matplotlib.")
        port = self.selected_port()
        if not port: return messagebox.showwarning("No board", "Connect the flight computer and press Refresh.")
        try:
            with serial.Serial(port, 115200, timeout=1): pass
            self.port = port; self.connection_label.configure(text=f"Connected: {port}", foreground="#176b3a"); self.log(f"Connected to {port}."); self.list_flights()
        except Exception as exc: messagebox.showerror("Connection failed", str(exc))

    def open_serial(self):
        if serial is None: raise RuntimeError("pyserial is not installed")
        port = self.port or self.selected_port()
        if not port: raise RuntimeError("No flight computer connected")
        return serial.Serial(port, 115200, timeout=1)

    def command(self, ser, command, end="FLASH:END"):
        ser.reset_input_buffer(); ser.write((command + "\n").encode()); lines = []
        deadline = time.time() + 3
        while time.time() < deadline:
            line = ser.readline().decode(errors="ignore").strip()
            if line: lines.append(line)
            if line == end: break
        return lines

    def list_flights(self):
        try:
            with self.open_serial() as ser: lines = self.command(ser, "LIST")
            self.flight_rows = [line for line in lines if line.startswith("FLASH:FLIGHT:")]
            self.flight_list.delete(0, "end")
            for row in self.flight_rows: self.flight_list.insert("end", row.replace("FLASH:FLIGHT:", ""))
            self.log(f"Found {len(self.flight_rows)} flight(s) on the board.")
        except Exception as exc: self.log(f"Could not list flights: {exc}")

    def flight_number(self):
        index = self.flight_list.curselection()
        if not index: return None
        match = re.search(r"flight_(\d+)", self.flight_rows[index[0]])
        return int(match.group(1)) if match else None

    def download(self, number, delete=False):
        FLIGHT_DIR.mkdir(exist_ok=True)
        with self.open_serial() as ser:
            ser.reset_input_buffer(); ser.write(f"GET {number}\n".encode()); data = bytearray(); started = False; deadline = time.time() + 8
            while time.time() < deadline:
                chunk = ser.read(ser.in_waiting or 1)
                if not chunk: continue
                if not started:
                    marker = chunk.find(b"FLASH:DATA_START\n")
                    if marker < 0: continue
                    chunk = chunk[marker + len(b"FLASH:DATA_START\n"):]; started = True
                end = chunk.find(b"FLASH:END")
                if end >= 0: data.extend(chunk[:end]); break
                data.extend(chunk); deadline = time.time() + 5
            if len(data) < RECORD_SIZE: raise RuntimeError("The board returned no complete flight records")
            stamp = datetime.now().strftime("%Y%m%d_%H%M%S"); path = FLIGHT_DIR / f"flight_{number}_{stamp}.csv"
            with path.open("w", newline="", encoding="utf-8") as output:
                writer = csv.writer(output); writer.writerow(["time_s", "altitude_m", "velocity_ms", "accel_bias_ms2", "raw_accel_ms2", "raw_baro_m", "motor_pos", "motor_vel", "motor_cmd_pos", "roll_rad", "pitch_rad", "yaw_rad", "Cd", "desired_Cd", "motor_current_A", "state", "axis_error"])
                for offset in range(0, len(data) - RECORD_SIZE + 1, RECORD_SIZE):
                    values = struct.unpack(RECORD_FORMAT, data[offset:offset + RECORD_SIZE]); state = STATE_NAMES[values[15]] if values[15] < len(STATE_NAMES) else f"UNKNOWN({values[15]})"
                    writer.writerow([values[0] / 1000.0, *[f"{v:.6f}" for v in values[1:15]], state, values[16]])
            if delete: ser.reset_input_buffer(); ser.write(f"DELETE {number}\n".encode())
        return path

    def download_selected(self):
        number = self.flight_number()
        if number is None: return messagebox.showinfo("Select a flight", "Select a flight first.")
        try: path = self.download(number); self.refresh_files(); self.log(f"Saved {path.name}.")
        except Exception as exc: messagebox.showerror("Download failed", str(exc))

    def download_all(self):
        try:
            with self.open_serial() as ser: lines = self.command(ser, "LIST")
            nums = [int(m.group(1)) for line in lines if "[ACTIVE]" not in line for m in [re.search(r"flight_(\d+)", line)] if m]
            for number in nums: self.download(number, delete=True)
            self.refresh_files(); self.log(f"Downloaded {len(nums)} flight(s) and cleared confirmed copies from the board.")
        except Exception as exc: messagebox.showerror("Download failed", str(exc))

    def delete_selected(self):
        number = self.flight_number()
        if number is None or not messagebox.askyesno("Delete flight", f"Delete flight {number} from the board? Download it first if you need it."): return
        try:
            with self.open_serial() as ser: self.command(ser, f"DELETE {number}", end="FLASH:DELETED")
            self.list_flights()
        except Exception as exc: messagebox.showerror("Delete failed", str(exc))

    def save_settings(self):
        try:
            mass = float(self.fields["MASS"].get()); temp = float(self.fields["TEMP_F"].get()); humidity = float(self.fields["HUMIDITY"].get()); pressure = float(self.fields["PRESSURE"].get())
            rho = density(temp, humidity, pressure); update_macro("MASS", f"{mass:.6f}"); update_macro("TARGET_ALTITUDE", f"{float(self.fields['TARGET_ALTITUDE'].get()):.3f}"); update_macro("BASE_CD", f"{float(self.fields['BASE_CD'].get()):.4f}"); update_macro("MOTOR_MIN", f"{float(self.fields['MOTOR_MIN'].get()):.3f}"); update_macro("MOTOR_MAX", f"{float(self.fields['MOTOR_MAX'].get()):.3f}"); update_macro("RHO", f"{rho:.6f}")
            write_coast_table(mass, rho); self.log(f"Saved launch settings. Air density: {rho:.4f} kg/m^3. Coast table regenerated.")
        except Exception as exc: messagebox.showerror("Settings error", str(exc))

    def generate(self): self.save_settings()

    def run_pio(self, target):
        pio = shutil.which("pio") or str(ROOT / ".pio" / "penv" / "Scripts" / "pio.exe")
        if not Path(pio).exists() and not shutil.which("pio"): return messagebox.showerror("PlatformIO not found", "Install PlatformIO Core once. After that this app handles builds and uploads without VS Code.")
        self.log(f"Running PlatformIO {target}...")
        def worker():
            try:
                args = [pio, "run", "-t", target] if target != "run" else [pio, "run"]
                if target == "upload": args += ["--upload-port", self.selected_port() or self.port]
                result = subprocess.run(args, cwd=ROOT, capture_output=True, text=True, timeout=240)
                self.after(0, lambda: self.log((result.stdout + result.stderr)[-4000:] if result.returncode else f"PlatformIO {target} completed successfully."))
            except Exception as exc: self.after(0, lambda: self.log(f"PlatformIO failed: {exc}"))
        threading.Thread(target=worker, daemon=True).start()

    def flash(self):
        if not (self.port or self.selected_port()): return messagebox.showwarning("No board", "Connect the flight computer before flashing.")
        self.save_settings(); self.run_pio("upload")

    def refresh_files(self):
        FLIGHT_DIR.mkdir(exist_ok=True); files = sorted(FLIGHT_DIR.glob("flight_*.csv"), reverse=True); self.file_box["values"] = [str(p) for p in files]
        if files: self.file_box.current(0)

    def plot_selected(self):
        if Figure is None: return messagebox.showerror("Missing dependency", "Install matplotlib to use flight plots.")
        path = Path(self.file_var.get())
        if not path.exists(): return
        with path.open(newline="", encoding="utf-8") as source: rows = list(csv.DictReader(source))
        if not rows: return
        def col(name): return [float(row[name]) for row in rows]
        for child in self.plot_frame.winfo_children(): child.destroy()
        fig = Figure(figsize=(10, 6), dpi=95); axes = fig.subplots(3, 2); t = col("time_s")
        charts = [("altitude_m", "Altitude", "m"), ("velocity_ms", "Velocity", "m/s"), ("raw_accel_ms2", "Acceleration", "m/s²"), ("motor_pos", "Motor position", "position"), ("Cd", "Cd", ""), ("desired_Cd", "Predicted/desired Cd", "")]
        for axis, (name, title, unit) in zip(axes.flat, charts): axis.plot(t, col(name), linewidth=1.2, label=name); axis.set_title(title); axis.set_xlabel("Time (s)"); axis.set_ylabel(unit); axis.grid(True, alpha=.25); axis.legend(loc="best", fontsize=8)
        fig.tight_layout(); canvas = FigureCanvasTkAgg(fig, master=self.plot_frame); canvas.draw(); canvas.get_tk_widget().pack(fill="both", expand=True)


if __name__ == "__main__":
    GroundStation().mainloop()
