"""
Loads the REAL coast lookup table from the user's repo
(sim/coast_table.py: VEL_RANGE, CD_RANGE, ALTITUDE_TABLE — the same
bilinear table src/control.cpp uses on-device, just regenerated as a
.py module instead of the .h version) and uses it to predict coast
performance for comparison against an actual flight.

Loaded fresh via importlib every time rather than a normal `import`,
because this file gets regenerated by generate_coast_table.py and we
always want the current on-disk version, not a stale cached one.
"""

import importlib.util
import os

import numpy as np


def load_coast_table(repo_path):
    """Returns (vel_range, cd_range, altitude_table) as numpy arrays."""
    path = os.path.join(repo_path, "sim", "coast_table.py")
    if not os.path.exists(path):
        raise FileNotFoundError(f"No coast table at {path}")
    spec = importlib.util.spec_from_file_location("_coast_table_live", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.VEL_RANGE, mod.CD_RANGE, mod.ALTITUDE_TABLE


def bilinear_lookup(vel_range, cd_range, table, vel, cd):
    """
    Vectorized bilinear interpolation into table[vel_index][cd_index].
    vel/cd may be scalars or numpy arrays; out-of-range inputs are
    clamped to the table's edges rather than extrapolated.
    """
    vel = np.clip(np.asarray(vel, dtype=float), vel_range[0], vel_range[-1])
    cd = np.clip(np.asarray(cd, dtype=float), cd_range[0], cd_range[-1])

    i = np.clip(np.searchsorted(vel_range, vel) - 1, 0, len(vel_range) - 2)
    j = np.clip(np.searchsorted(cd_range, cd) - 1, 0, len(cd_range) - 2)

    v0, v1 = vel_range[i], vel_range[i + 1]
    c0, c1 = cd_range[j], cd_range[j + 1]
    tv = np.divide(vel - v0, v1 - v0, out=np.zeros_like(vel), where=(v1 != v0))
    tc = np.divide(cd - c0, c1 - c0, out=np.zeros_like(cd), where=(c1 != c0))

    f00 = table[i, j]
    f10 = table[i + 1, j]
    f01 = table[i, j + 1]
    f11 = table[i + 1, j + 1]
    return (f00 * (1 - tv) * (1 - tc) + f10 * tv * (1 - tc)
            + f01 * (1 - tv) * tc + f11 * tv * tc)


def predicted_remaining_altitude(df, vel_range, cd_range, table, cd_column="Cd"):
    """
    For each row of the flight, predicts how much MORE altitude will be
    gained from here to apogee if the rocket coasts at its current
    velocity and Cd — this is the same lookup the onboard bisection
    search (control.cpp's getCoastAltitude()) uses in real time.
    Returns a numpy array aligned with df's rows.
    """
    return bilinear_lookup(vel_range, cd_range, table,
                            df["velocity_ms"].to_numpy(),
                            df[cd_column].to_numpy())
