"""
Generic #define editor for include/config.h.

This is intentionally format-driven rather than hardcoded to specific field
names (TARGET_ALTITUDE, MOTOR_MIN, etc.) — it parses ANY line of the form

    #define NAME  VALUE          // optional trailing comment

into an editable row, using the trailing comment as the on-screen help text.
It skips function-like macros (`#define FOO(x) ...`) and include guards.

When saving, only the VALUE token on each matched line is replaced — every
other line, comment, and the original ordering is left completely untouched,
so this is safe to run on a hand-tuned config.h without reformatting it.

NOTE: this was built without seeing your actual config.h. If your constants
use a different style (e.g. `constexpr float X = ...;` instead of #define),
send me the file and I'll adjust DEFINE_RE below in five minutes.
"""

import re

DEFINE_RE = re.compile(
    r"^(?P<indent>\s*)#define\s+(?P<name>[A-Za-z_][A-Za-z0-9_]*)"
    r"(?!\s*\()"                       # not function-like: NAME( is excluded
    r"\s+(?P<value>[^\s/]+)"
    r"(?P<tail>\s*(?://\s*(?P<comment>.*))?)\s*$"
)

# Names that are almost always include guards / not tunable values.
SKIP_PATTERNS = (re.compile(r".*_H$"), re.compile(r".*_H_$"))


class ConfigField:
    AUTO_GEN_HINTS = ("auto-generated", "auto generated", "regenerated by")

    def __init__(self, name, value, comment, line_index):
        self.name = name
        self.value = value
        self.comment = comment or ""
        self.line_index = line_index
        self.is_auto_generated = any(
            hint in self.comment.lower() for hint in self.AUTO_GEN_HINTS)

    def is_numeric(self):
        try:
            float(self.value.rstrip("fF"))
            return True
        except ValueError:
            return False


class ConfigFile:
    def __init__(self, path):
        self.path = path
        with open(path) as f:
            self.lines = f.readlines()
        self._line_in_block_comment = self._find_block_comment_lines(self.lines)
        self.fields = self._parse()

    @staticmethod
    def _find_block_comment_lines(lines):
        """Returns a list[bool], one per line, True if that line's START
        falls inside an open /* ... */ block comment (so a #define there
        is commented out and must never be treated as live config)."""
        in_comment = False
        result = []
        for line in lines:
            result.append(in_comment)
            idx = 0
            while True:
                if in_comment:
                    end = line.find("*/", idx)
                    if end == -1:
                        break
                    in_comment = False
                    idx = end + 2
                else:
                    start = line.find("/*", idx)
                    line_comment = line.find("//", idx)
                    if start == -1:
                        break
                    if line_comment != -1 and line_comment < start:
                        break  # rest of line is a // comment; no /* here counts
                    in_comment = True
                    idx = start + 2
        return result

    def _parse(self):
        fields = []
        for i, line in enumerate(self.lines):
            if self._line_in_block_comment[i]:
                continue  # commented-out #define — not live config
            m = DEFINE_RE.match(line)
            if not m:
                continue
            name = m.group("name")
            if any(p.match(name) for p in SKIP_PATTERNS):
                continue
            fields.append(ConfigField(name, m.group("value"), m.group("comment"), i))
        return fields

    def set_value(self, name, new_value):
        for field in self.fields:
            if field.name == name:
                new_value = str(new_value).strip()
                # Preserve the original's `f` float-literal suffix if the
                # user's new value doesn't already specify one.
                if field.value.endswith(("f", "F")) and not new_value.endswith(("f", "F")):
                    try:
                        float(new_value)
                        new_value += "f"
                    except ValueError:
                        pass
                field.value = new_value
                line = self.lines[field.line_index]
                m = DEFINE_RE.match(line)
                start, end = m.span("value")
                self.lines[field.line_index] = line[:start] + new_value + line[end:]
                return True
        return False

    def save(self, out_path=None):
        with open(out_path or self.path, "w") as f:
            f.writelines(self.lines)
