#ifndef CONFIG_H
#define CONFIG_H

#include "math.h"

#define MASS 0.640000f         // kg (auto-generated by generate_coast_table.py)
#define BASE_CD 0.492f       // From OpenRocket
#define LAUNCH_ACCEL 30.0f  // m/s^2, acceleration at launch detection
#define LAUNCH_VEL 1.0f     // m/s, velocity at launch detection (real: 4.5)
#define MOTOR_MIN_BURN_TIME_MS 1200UL  // Never enter control during motor burn
#define VEL_CONTROL_START 55.0f  // m/s, vel drops below this to start control
#define VEL_DESCENT -1.0f        // m/s, vel drops below this to go to DESCENT
#define ALT_LANDED 2.0f          // m, alt below this to consider landed
#define VEL_LANDED 1.0f          // m/s, abs(vel) below this to consider landed
#define TARGET_ALTITUDE 243.84f   // m, target apogee altitude
#define MOTOR_MAX -42.0f         // Motor position for fully open
#define MOTOR_MIN 0.0f           // Motor position for fully closed

// Ground-test safety limits.  The test sweep is deliberately slow and stops
// immediately if the ODrive reports more than this torque-producing current.
#define GROUND_TEST_SHAKE_ACCEL 14.0f       // m/s^2, accel magnitude including gravity
#define GROUND_TEST_DURATION_MS 15000UL     // recording time after the shake
#define GROUND_TEST_SWEEP_STEP 2.0f         // position units per command
#define GROUND_TEST_SWEEP_PERIOD_MS 100UL   // 20 position units/s maximum
#define GROUND_TEST_CURRENT_LIMIT_A 3.0f
#define GROUND_TEST_VELOCITY_LIMIT 50.0f  // turns/s while executing the test
#define GROUND_TEST_POSITION_TOLERANCE 0.5f
#define GROUND_TEST_OPEN_TIMEOUT_MS 5000UL

// Cd controller tuning (closed-loop Cd tracking)
#define CD_CTRL_KP 5.0f             // position units per Cd error
#define CD_CTRL_KI 25.0f            // position units per (Cd error * s)
#define CD_CTRL_ERR_DEADBAND 0.01f  // Cd deadband to reduce chatter
#define CD_CTRL_DT_NOMINAL 0.002f   // s, fallback dt when timing is invalid

// Constants
#define AREA (M_PI * (6.6f / 100.0f) * (6.6f / 100.0f)) / 4.0f  // m^2
#define RHO 1.200433f                                              // kg/m^3 (from 68.0F, 55.0% RH)
#define G 9.80665f                  // m/s^2
constexpr float rhoA = RHO * AREA;  // Precomputed RHO * A

/*

// Baro compensation for airbrake pressure effect
#define BARO_COMP_COEFF 0.12f  // Compensation coefficient
#define BARO_COMP_DELAY_MS \
  40  // Delay between airbrake opening and baro effect (ms)

*/

#endif  // CONFIG_H
