#ifndef CONFIG_H
#define CONFIG_H

#include "math.h"

// Changes
#define MASS 0.607000f      // kg (auto-generated by generate_coast_table.py)
#define BASE_CD 0.44f       // From OpenRocket
#define LAUNCH_ACCEL 30.0f  // m/s^2, acceleration at launch detection
#define LAUNCH_VEL 1.0f     // m/s, velocity at launch detection (real: 4.5)
#define VEL_CONTROL_START 55.0f  // m/s, vel drops below this to start control
#define VEL_DESCENT -1.0f        // m/s, vel drops below this to go to DESCENT
#define ALT_LANDED 2.0f          // m, alt below this to consider landed
#define VEL_LANDED 1.0f          // m/s, abs(vel) below this to consider landed
#define TARGET_ALTITUDE 228.6f   // m, target apogee altitude
#define MOTOR_MAX 22.0f          // Motor position for fully open
#define MOTOR_MIN 0.0f           // Motor position for fully closed

// Cd controller tuning (closed-loop Cd tracking)
#define CD_CTRL_KP 5.0f             // position units per Cd error
#define CD_CTRL_KI 25.0f            // position units per (Cd error * s)
#define CD_CTRL_ERR_DEADBAND 0.01f  // Cd deadband to reduce chatter
#define CD_CTRL_DT_NOMINAL 0.002f   // s, fallback dt when timing is invalid

// Constants
#define AREA (M_PI * (6.6f / 100.0f) * (6.6f / 100.0f)) / 4.0f  // m^2
#define RHO 1.239432f               // kg/m^3 (from 55.0F, 49.0% RH)
#define G 9.80665f                  // m/s^2
constexpr float rhoA = RHO * AREA;  // Precomputed RHO * A

// Baro compensation for airbrake pressure effect
#define BARO_COMP_COEFF 0.12f  // Compensation coefficient
#define BARO_COMP_DELAY_MS \
  40  // Delay between airbrake opening and baro effect (ms)

#endif  // CONFIG_H