const $=s=>document.querySelector(s),api=window.groundStation;let flights=[];
const themeStyle=document.createElement('style');themeStyle.textContent='body.dark{--bg:#11161c;--panel:#1b222b;--panel2:#202a35;--line:#34414e;--text:#edf2f7;--muted:#9aaaba;--cyan:#35c1b4;--green:#55c985;--orange:#e4a14a;--pink:#ef78a4;color-scheme:dark}body.dark header{background:#171d24}body.dark button,body.dark select,body.dark input{background:#202a35;border-color:#43515f;color:var(--text)}body.dark button:hover,body.dark select:hover{background:#2a3643;border-color:#617181}body.dark .tab.active{background:#173b3a;border-color:#2d8e85;color:#8fe5dd}body.dark .monitor,body.dark pre{background:#141a21;color:#d7e0e8}body.dark .field,body.dark .hud>div{background:#202a35}body.dark .analytics{background:#1b222b}body.dark #r3dStage{background:#151b22}body.dark .r3d-hint{background:rgba(24,31,39,.88)}body.dark .toast{background:#202a35;box-shadow:0 8px 24px rgba(0,0,0,.35)}.theme-toggle{white-space:nowrap}';document.head.append(themeStyle);const themeButton=document.createElement('button');themeButton.id='themeToggle';themeButton.className='theme-toggle';themeButton.type='button';document.querySelector('header')?.append(themeButton);function setTheme(mode){const dark=mode==='dark';document.body.classList.toggle('dark',dark);themeButton.textContent=dark?'☀ Light mode':'☾ Dark mode';themeButton.setAttribute('aria-label',dark?'Switch to light mode':'Switch to dark mode');localStorage.setItem('airbrakes-theme',dark?'dark':'light')}themeButton.onclick=()=>setTheme(document.body.classList.contains('dark')?'light':'dark');setTheme(localStorage.getItem('airbrakes-theme')||'light');
const battery=document.createElement('article');battery.className='card span4';battery.innerHTML='<div class="title">BATTERY</div><div id="batteryVoltage" style="font-size:32px;font-weight:800;color:var(--cyan)">--.-- V</div><div id="batteryStatus" class="hint">Waiting for live telemetry</div>';document.querySelector('#ops .grid').prepend(battery);
api.on('serial-line',m=>{const match=m.match(/^BATTERY_VOLTAGE:(-?\d+(?:\.\d+)?)$/);if(match){$('#batteryVoltage').textContent=`${Number(match[1]).toFixed(2)} V`;$('#batteryStatus').textContent=`Live - updated ${new Date().toLocaleTimeString()}`}});
function toast(m,e=false){const x=$('#toast');x.textContent=m;x.className=`toast show${e?' error':''}`;clearTimeout(toast.t);toast.t=setTimeout(()=>x.className='toast',4200)}function log(m){const x=$('#log');x.textContent+=`\n${m}`;x.scrollTop=x.scrollHeight}async function run(label,fn){$('#opstatus').textContent=`${label}…`;toast(`${label}…`);try{const x=await fn();$('#opstatus').textContent=`${label} complete`;toast(typeof x==='string'?x:`${label} complete`);return x}catch(e){$('#opstatus').textContent=`${label} failed`;toast(e.message,true);if(/Building|Flashing/.test(label))log(`ERROR: ${e.message}`);throw e}}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-view],.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(`#${b.dataset.view}`).classList.add('active')});document.querySelectorAll('[data-config]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-config],.config-page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(`#${b.dataset.config}`).classList.add('active')});
async function refresh(){const p=await api.ports(),box=$('#ports');box.innerHTML='';p.forEach(v=>box.add(new Option(v.label,v.path)));if(!p.length)box.add(new Option('No serial ports found',''));toast(p.length?`${p.length} serial port(s) found`:'No serial ports found',!p.length)}function connected(info,device=''){ $('#conn').textContent='● CONNECTED';$('#conn').classList.add('online');$('#storage').textContent=`${device?'Connected to '+device+'. ':''}Storage: ${info}`}
$('#refresh').onclick=()=>run('Refreshing serial ports',refresh);$('#connect').onclick=async()=>{const p=$('#ports').value;if(!p)return toast('Choose a serial port first',true);connected(await run('Connecting',()=>api.connect(p)),p)};$('#auto').onclick=async()=>{const r=await run('Auto-connecting',api.autoConnect);connected(r.info,r.path);await refresh()};$('#disconnect').onclick=async()=>{await api.disconnect();$('#conn').textContent='● OFFLINE';$('#conn').classList.remove('online');$('#storage').textContent='Disconnected.';toast('Disconnected')};document.querySelectorAll('[data-cmd]').forEach(b=>b.onclick=()=>run(b.textContent,()=>api.command(b.dataset.cmd)));$('#arm').onclick=()=>run('Arming ground test',()=>api.command('GROUND_TEST START'));$('#abort').onclick=()=>run('Aborting ground test',()=>api.command('GROUND_TEST ABORT'));$('#build').onclick=()=>run('Building firmware',api.build);$('#flash').onclick=()=>run('Flashing firmware',api.flash);$('#generate').onclick=()=>run('Regenerating coast table',api.generateCoast);
async function config(){const r=await api.readDefines(),shell=$('#fields');shell.innerHTML='';r.values.forEach(v=>{const e=document.createElement('div');e.className='field';e.innerHTML=`<label>${v.name}</label><small>${v.comment||'Configuration value'}</small><input data-name="${v.name}" value="${v.value}">`;shell.append(e)})}$('#reloadConfig').onclick=()=>run('Loading config.h',config);$('#saveConfig').onclick=()=>run('Saving config.h',()=>api.saveDefines([...document.querySelectorAll('#fields input')].map(x=>({name:x.dataset.name,value:x.value}))));api.on('serial-line',m=>{const x=$('#serial');x.textContent+=`\n${m}`;x.scrollTop=x.scrollHeight});api.on('pio-log',log);api.on('download-progress',p=>$('#opstatus').textContent=`Downloading ${p.received}/${p.expected} bytes`);refresh().catch(()=>{});config().catch(e=>toast(e.message,true));
async function listFlights(){flights=await run('Listing device flights',api.listFlights);const shell=$('#flightList');shell.innerHTML=flights.length?'':'No saved flights on the board.';flights.forEach(f=>{const row=document.createElement('div');row.className='flight';row.innerHTML=`<span>${f.label}</span><span><button>Download</button> <button class="danger">Delete</button></span>`;row.querySelector('button').onclick=()=>run(`Downloading flight ${f.num}`,()=>api.download(f.num)).then(r=>toast(`${r.records} records saved`));row.querySelector('.danger').onclick=()=>confirm(`Delete flight ${f.num} from the board?`)&&run(`Deleting flight ${f.num}`,()=>api.deleteFlight(f.num)).then(listFlights);shell.append(row)})}$('#listFlights').onclick=listFlights;$('#downloadAll').onclick=async()=>{if(!flights.length)await listFlights();for(const f of flights)if(!f.active)await run(`Downloading flight ${f.num}`,()=>api.download(f.num));toast('All non-active flights downloaded')};$('#openData').onclick=()=>run('Opening flight folder',api.openData);
// Safety strip and local-log management are intentionally separate from the
// on-board flight list: a ground test is never presented as a flight.
api.on('connection-state',state=>{if(state.connected) connected(state.info,state.device);else {$('#conn').textContent='● OFFLINE';$('#conn').classList.remove('online');$('#storage').textContent='Board disconnected. Searching automatically...';$('#batteryVoltage').textContent='--.-- V';$('#batteryStatus').textContent='Waiting for live telemetry'}});
const local=document.createElement('section');local.className='card';local.innerHTML='<div class="title">LOCAL LOGS</div><div class="actions"><button id="localFlights">Flights</button><button id="localGround">Ground tests</button></div><div id="localList" class="status">Choose a category to manage local logs.</div>';document.querySelector('#analytics').insertBefore(local,document.querySelector('.analytics-embedded'));
api.autoConnect().then(r=>{if(r.path)connected(r.info,r.path)}).catch(()=>{});
async function showLocal(category){const entries=await api.localEntries(category);const shell=$('#localList');shell.innerHTML=entries.length?'':`No saved ${category.replace('_',' ')}.`;entries.forEach(e=>{const row=document.createElement('div');row.className='flight';row.innerHTML=`<span>${e.folder} · ${e.num_records||0} records</span><button class="danger">Delete locally</button>`;row.querySelector('button').onclick=async()=>{if(confirm(`Permanently delete local ${e.folder}?`)){await api.localDelete(category,e.folder);showLocal(category)}};shell.append(row)})}$('#localFlights').onclick=()=>showLocal('flights');$('#localGround').onclick=()=>showLocal('ground_tests');
