const $=s=>document.querySelector(s),api=window.groundStation;let flights=[];
function toast(m,e=false){const x=$('#toast');x.textContent=m;x.className=`toast show${e?' error':''}`;clearTimeout(toast.t);toast.t=setTimeout(()=>x.className='toast',4200)}function log(m){const x=$('#log');x.textContent+=`\n${m}`;x.scrollTop=x.scrollHeight}async function run(label,fn){$('#opstatus').textContent=`${label}…`;toast(`${label}…`);try{const x=await fn();$('#opstatus').textContent=`${label} complete`;toast(typeof x==='string'?x:`${label} complete`);return x}catch(e){$('#opstatus').textContent=`${label} failed`;toast(e.message,true);log(`ERROR: ${e.message}`);throw e}}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-view],.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(`#${b.dataset.view}`).classList.add('active')});document.querySelectorAll('[data-config]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-config],.config-page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(`#${b.dataset.config}`).classList.add('active')});
async function refresh(){const p=await api.ports(),box=$('#ports');box.innerHTML='';p.forEach(v=>box.add(new Option(v.label,v.path)));if(!p.length)box.add(new Option('No serial ports found',''));toast(p.length?`${p.length} serial port(s) found`:'No serial ports found',!p.length)}function connected(info,device=''){ $('#conn').textContent='● CONNECTED';$('#conn').classList.add('online');$('#storage').textContent=`${device?'Connected to '+device+'. ':''}Storage: ${info}`}
$('#refresh').onclick=()=>run('Refreshing serial ports',refresh);$('#connect').onclick=async()=>{const p=$('#ports').value;if(!p)return toast('Choose a serial port first',true);connected(await run('Connecting',()=>api.connect(p)),p)};$('#auto').onclick=async()=>{const r=await run('Auto-connecting',api.autoConnect);connected(r.info,r.path);await refresh()};$('#disconnect').onclick=async()=>{await api.disconnect();$('#conn').textContent='● OFFLINE';$('#conn').classList.remove('online');$('#storage').textContent='Disconnected.';toast('Disconnected')};document.querySelectorAll('[data-cmd]').forEach(b=>b.onclick=()=>run(b.textContent,()=>api.command(b.dataset.cmd)).then(log));$('#arm').onclick=()=>run('Arming ground test',()=>api.command('GROUND_TEST START')).then(log);$('#abort').onclick=()=>run('Aborting ground test',()=>api.command('GROUND_TEST ABORT')).then(log);$('#build').onclick=()=>run('Building firmware',api.build);$('#flash').onclick=()=>run('Flashing firmware',api.flash);$('#generate').onclick=()=>run('Regenerating coast table',api.generateCoast);
async function config(){const r=await api.readDefines(),shell=$('#fields');shell.innerHTML='';r.values.forEach(v=>{const e=document.createElement('div');e.className='field';e.innerHTML=`<label>${v.name}</label><small>${v.comment||'Configuration value'}</small><input data-name="${v.name}" value="${v.value}">`;shell.append(e)})}$('#reloadConfig').onclick=()=>run('Loading config.h',config);$('#saveConfig').onclick=()=>run('Saving config.h',()=>api.saveDefines([...document.querySelectorAll('#fields input')].map(x=>({name:x.dataset.name,value:x.value}))));api.on('serial-line',m=>{const x=$('#serial');x.textContent+=`\n${m}`;x.scrollTop=x.scrollHeight;log(m)});api.on('operation-log',log);api.on('download-progress',p=>$('#opstatus').textContent=`Downloading ${p.received}/${p.expected} bytes`);refresh().catch(()=>{});config().catch(e=>toast(e.message,true));
async function listFlights(){flights=await run('Listing device flights',api.listFlights);const shell=$('#flightList');shell.innerHTML=flights.length?'':'No saved flights on the board.';flights.forEach(f=>{const row=document.createElement('div');row.className='flight';row.innerHTML=`<span>${f.label}</span><span><button>Download</button> <button class="danger">Delete</button></span>`;row.querySelector('button').onclick=()=>run(`Downloading flight ${f.num}`,()=>api.download(f.num)).then(r=>toast(`${r.records} records saved`));row.querySelector('.danger').onclick=()=>confirm(`Delete flight ${f.num} from the board?`)&&run(`Deleting flight ${f.num}`,()=>api.deleteFlight(f.num)).then(listFlights);shell.append(row)})}$('#listFlights').onclick=listFlights;$('#downloadAll').onclick=async()=>{if(!flights.length)await listFlights();for(const f of flights)if(!f.active)await run(`Downloading flight ${f.num}`,()=>api.download(f.num));toast('All non-active flights downloaded')};$('#openData').onclick=()=>run('Opening flight folder',api.openData);
// Safety strip and local-log management are intentionally separate from the
// on-board flight list: a ground test is never presented as a flight.
const health=document.createElement('div');health.id='health';health.className='status';health.innerHTML='IMU <b>UNKNOWN</b> · DPS368 <b>UNKNOWN</b> · ODrive <b>UNKNOWN</b>';document.querySelector('header').append(health);
const oldConnected=connected;connected=(info,device)=>{oldConnected(info,device);health.innerHTML='IMU <b>CHECK REQUIRED</b> · DPS368 <b>CHECK REQUIRED</b> · ODrive <b>CHECK REQUIRED</b>'};document.querySelector('#disconnect').addEventListener('click',()=>{health.innerHTML='IMU <b>NOT CONNECTED</b> · DPS368 <b>NOT CONNECTED</b> · ODrive <b>NOT CONNECTED</b>'});
const local=document.createElement('section');local.className='card';local.innerHTML='<div class="title">LOCAL LOGS</div><div class="actions"><button id="localFlights">Flights</button><button id="localGround">Ground tests</button></div><div id="localList" class="status">Choose a category to manage local logs.</div>';document.querySelector('#analytics').insertBefore(local,document.querySelector('.analytics'));
async function showLocal(category){const entries=await api.localEntries(category);const shell=$('#localList');shell.innerHTML=entries.length?'':`No saved ${category.replace('_',' ')}.`;entries.forEach(e=>{const row=document.createElement('div');row.className='flight';row.innerHTML=`<span>${e.folder} · ${e.num_records||0} records</span><button class="danger">Delete locally</button>`;row.querySelector('button').onclick=async()=>{if(confirm(`Permanently delete local ${e.folder}?`)){await api.localDelete(category,e.folder);showLocal(category)}};shell.append(row)})}$('#localFlights').onclick=()=>showLocal('flights');$('#localGround').onclick=()=>showLocal('ground_tests');
